name: Test App Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect tag info
        shell: bash
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_SHA=${{ github.sha }}" >> $GITHUB_ENV
          COMMIT_DATE=$(git log -1 --format=%cI $GITHUB_SHA)
          echo "TAG_TIMESTAMP=$COMMIT_DATE" >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_mingw81'
          cache: true

      - name: Install MinGW with Chocolatey
        run: |
          choco install mingw --forcex86 --version=8.1.0 -y

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="C:\ProgramData\chocolatey\bin\gcc.exe" -DCMAKE_CXX_COMPILER="C:\ProgramData\chocolatey\bin\g++.exe" -DCMAKE_LINKER="C:\ProgramData\chocolatey\bin\ld.exe"

      - name: Build Project
        run: cmake --build build --config Release

      - name: Deploy
        run: |
          mkdir deploy
          cp build\testrepo.exe deploy\
          D:\a\testrepo\Qt\5.15.2\mingw81_32\bin\windeployqt.exe deploy
          cp C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\libgcc_s_dw2-1.dll deploy\
          cp C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\libstdc++-6.dll deploy\
          cp C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\libwinpthread-1.dll deploy\

      - name: Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: testrepo-Win-32
          path: deploy

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: testrepo-Win-32
          path: deploy/

      - name: Create ZIP Archive
        run: |
          zip -r testrepo-Win32-${{ github.ref_name }}.zip deploy/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: testrepo-Win32-${{ github.ref_name }}.zip
          asset_name: testrepo-Win32-${{ github.ref_name }}.zip
          asset_content_type: application/zip
